###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "2.0"
services:

    php:
        build: ./php
        container_name: "${DOCKER_PREFIX}-http"
        #working_dir: /application
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - ./apache2/sites-enabled:/etc/apache2/sites-enabled
            - "${HTTP_DIR}:/var/www/html"
            - ./php/log/apache2:/var/log/apache2
#        - .:/application
#        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
        networks:
            dapmmr-static-network:
                ipv4_address: ${HTTP_DOCKER_IP}
        tty: true

    db:
        image: mysql:5.6
        container_name: "${DOCKER_PREFIX}-mysql"
        command: --max_allowed_packet=4096M
        volumes:
            - ./mysql/db_data:/var/lib/mysql
            - ./mysql/home:/home
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
            - MYSQL_DATABASE=${MYSQL_DB}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASS}
        networks:
            dapmmr-static-network:
                ipv4_address: ${MYSQL_DOCKER_IP}

    redis:
        image: redis
        container_name: "${DOCKER_PREFIX}-redis"
        ports:
            - "${REDIS_PORT}:6379"
        networks:
            dapmmr-static-network:
                ipv4_address: ${REDIS_DOCKER_IP}

    # mssql:
    #     image: microsoft/mssql-server-linux
    #     container_name: server-mssql
    #     volumes:
    #         - ./mssql/var_opt_mssql:/var/opt/mssql
    #         - ./mssql/var_opt_mssql/data:/var/opt/mssql/data
    #     environment:
    #         ACCEPT_EULA: "Y"
    #         SA_PASSWORD: "server!!!"
    #     ports:
    #         - "1433:1433"
    #     networks:
    #         static-network:
    #             ipv4_address: 172.20.128.5

networks:
    dapmmr-static-network:
        ipam:
            config:
                - subnet: ${NETWORK_SUBNET}
                  ip_range: ${NETWORK_IP_RANGE}
